"""Injects the corpus' BibTeX entries into the article's biblio.bib.

Reads every row's ``BIBTEX`` cell via ``data_loader.load_corpus()`` and
writes them between two marker comments in ``config.BIBLIO_BIB``. Also
writes a ready-to-paste ``\\cite{...}`` command (all keys at once) to
``OUTPUT_BASE_DIR/citations.txt``.

Never edit the content between the markers by hand — it is overwritten
every run.
"""

import re

import config
from data_loader import load_corpus

DELIMITER_START = "% AUTOGENERATED-BIBTEX-START"
DELIMITER_END = "% AUTOGENERATED-BIBTEX-END"


def generate_bibtex_and_citations(output_bib=None, output_cite=None):
    output_bib = output_bib or config.BIBLIO_BIB
    output_cite = output_cite or (config.OUTPUT_BASE_DIR / "citations.txt")

    df = load_corpus()

    bib_entries = []
    cite_keys = []

    for _, row in df[["ID", "KEY", "BIBTEX"]].iterrows():
        bib = str(row["BIBTEX"]).strip()
        if not bib.startswith("@"):
            continue
        bib_entries.append(f"% Row ID: {row['ID']}\n{bib}\n\n")
        cite_keys.append(str(row["KEY"]).strip())

    new_section = f"{DELIMITER_START}\n\n" + "".join(bib_entries) + f"{DELIMITER_END}\n"

    if not output_bib.exists():
        # First run against a fresh article repo: seed the file with just the markers.
        output_bib.parent.mkdir(parents=True, exist_ok=True)
        output_bib.write_text(f"{DELIMITER_START}\n{DELIMITER_END}\n", encoding="utf-8")
        print(f"'{output_bib}' did not exist — created it with empty markers.")

    content = output_bib.read_text(encoding="utf-8")

    pattern = re.compile(
        re.escape(DELIMITER_START) + r".*?" + re.escape(DELIMITER_END),
        re.DOTALL,
    )
    if not pattern.search(content):
        print(f"Error: Delimiters '{DELIMITER_START}' / '{DELIMITER_END}' not found in '{output_bib}'.")
        return

    content = pattern.sub(lambda _: new_section.strip(), content)
    output_bib.write_text(content, encoding="utf-8")

    output_cite.parent.mkdir(parents=True, exist_ok=True)
    output_cite.write_text(f"\\cite{{{', '.join(cite_keys)}}}", encoding="utf-8")

    print(f"Entries exported: {len(bib_entries)}")
    print(f"Updated '{output_bib}'")
    print(f"Citation command written to '{output_cite}'")


if __name__ == "__main__":
    generate_bibtex_and_citations()
